### PR TITLE
Dokan 0.7.3 support

### PR DESCRIPTION
**Pull request by landrix**
- Dokan 0.7.3 support
- Win32, Win64 support

### CODE REVIEW

**Comment by Liryna** [comment]
Thanks of the PR
I am not really familiar with delphi but it seems to be good :smiley: 
Are you only using dokan with delphi ?

We will probably wait the @Maxhy review before merging it.

**Comment by landrix** [comment]
i try dokan with delphi and .net

At the moment I still check, it would be better to create the mountpoint on the client or on server over network-share. But I'm still missing a few basics (see also my question in dokan google group)

**Comment by Maxhy** [comment]
Thanks for this PR @landrix.
This looks good, except _Mirror.dproj_ file:
- Excluded package list looks too specific to your environment
- Import Project declarations add new build tool dependencies (CodeGear, Embarcadero).
  Or did I misread the code?

**Comment by landrix** [comment]
There are no dependencies. The exclude and import parts can be removed. Should I start a new pull request?

**Comment by landrix** [comment]
or remove the complete dproj file

**Comment by Maxhy** [comment]
Ok, well I believe the prerequisite to open Dproj file will be to have Embarcadero installed then.
After thinking we can keep it for other peoples using this tool, today there is no dproj file so this is not a regression. I will merge as it is. Thank you (btw to update a PR you just have to push new commits to your branch, no need for a new PR).

**Pull request merged**
