### PR TITLE
Support Dokany 0.8.0-RC2

### PR DESCRIPTION
**Pull request by landrix**

### CODE REVIEW

**Comment by Liryna** [comment]
WOW  :open_mouth: My hero !
Thats look amazing. Is it really working ?

If you want to become the main maintainer of dokan-delphi, you just need to ask :heart: The place is free !

**Comment by landrix** [comment]
Yes,all used function from previous release works again. only EnumerateNamedStreams isn't testet.

Yes,i want to be the main maintainer.

**Comment by Liryna** [comment]
Invitation sended :+1: 
And Thanks a lot for contributing and helping this project to rock !

Welcome to the Dokan-dev team :)

**Comment by landrix** [comment]
:)

**Comment by Liryna** [comment]
For informations, I had to change the EnumerateNamedStreams prototype https://github.com/dokan-dev/dokany/commit/7799f883acd08d75dbcf185d6dd53581f845a3bb for the futur 0.8.0-RC3

**Pull request merged**
